package io.github.latcn.a2a.permission.api.enums;

public enum OperationType {
    ROLE_GRANT, ROLE_REVOKE,
    PERM_GRANT, PERM_REVOKE,
    ROW_RULE_UPDATE,
    ROLE_CREATE, ROLE_UPDATE, ROLE_DELETE,
    PERM_CREATE, PERM_UPDATE, PERM_DELETE,
    ACL_CREATE, ACL_UPDATE, ACL_DELETE,
    AGENT_REGISTER, AGENT_UPDATE, AGENT_SUSPEND, AGENT_ACTIVATE, AGENT_SECRET_ROTATE
}
